services:
  server:
    container_name: reservation-service
    build:
      context: ./backend/src
      target: final
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./front
    ports:
      - 3000:80  
    environment:
      - NODE_ENV=development  
    depends_on:
      - server

  db:
    container_name: postgres-database
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=cute
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432 
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
        
volumes:
  db-data:
